<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Razor.Core\Razor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Chrysalis.Codec" Version="1.4.0-alpha" />
    <PackageReference Include="Utxorpc.Spec" Version="0.18.1-alpha" />
  </ItemGroup>

</Project>
