<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Razor.Core\Razor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Chrysalis\src\Chrysalis.Cbor\Chrysalis.Cbor.csproj" />
    <PackageReference Include="Utxorpc.Spec" Version="0.18.1-alpha" />
  </ItemGroup>

</Project>
