<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Razor.Core\Razor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Utxorpc.Spec" Version="0.18.1-alpha" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
