<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Razor.Core\Razor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Chrysalis\src\Chrysalis.Network\Chrysalis.Network.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
  </ItemGroup>

</Project>
